[theme]
primaryColor = "#E31837"            
backgroundColor = "#ffffffff"         
secondaryBackgroundColor = "#F5F5F5"
textColor = "#333333"              
font = "sans serif"     
borderColor = "#BE0F29"        